name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      #
      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run ESLint
        run: |
          cd backend
          npm run lint

      - name: Run Tests
        run: |
          cd backend
          npm test

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t quiz-backend .     